### ISSUE TITLE
Flaky watchdog unit tests: test_3_daemon_with_watchdog/python_test_osqueryd (assertion errors)

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#1220]
While building and testing on RHEL6.5 (merged from master yesterday), I've been reliably getting an Assertion Error from `make test`.  

```
Running tests...
Test project /root/osquery/build/rhel6
    Start 1: osquery_tests
1/9 Test #1: osquery_tests ....................   Passed    0.36 sec
    Start 2: osquery_additional_tests
2/9 Test #2: osquery_additional_tests .........   Passed    5.53 sec
    Start 3: osquery_tables_tests
3/9 Test #3: osquery_tables_tests .............   Passed    0.14 sec
    Start 4: python_test_osqueryi
4/9 Test #4: python_test_osqueryi .............   Passed    7.89 sec
    Start 5: python_test_osqueryd
5/9 Test #5: python_test_osqueryd .............***Failed    1.71 sec
.I0619 20:21:58.394845 24438 config.cpp:129] Verbose logging enabled by config option
I0619 20:21:58.396441 24439 events.cpp:429] Starting event publisher run loop: inotify
I0619 20:21:58.396474 24440 events.cpp:429] Starting event publisher run loop: udev
.F
======================================================================
FAIL: test_3_daemon_with_watchdog (__main__.DaemonTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/osquery/tools/tests/test_osqueryd.py", line 62, in test_3_daemon_with_watchdog
    self.assertTrue(len(children) > 0)
AssertionError

----------------------------------------------------------------------
Ran 3 tests in 0.614s

FAILED (failures=1)

    Start 6: python_test_modules
6/9 Test #6: python_test_modules ..............   Passed    3.28 sec
    Start 7: python_test_extensions
7/9 Test #7: python_test_extensions ...........   Passed    6.00 sec
    Start 8: python_test_additional
8/9 Test #8: python_test_additional ...........   Passed    1.32 sec
    Start 9: python_test_example_queries
9/9 Test #9: python_test_example_queries ......   Passed    3.27 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) =  29.52 sec

The following tests FAILED:
	  5 - python_test_osqueryd (Failed)
Errors while running CTest
make[1]: *** [test] Error 8
make: *** [test] Error 2
```

**Comment by theopolis** [comment]
This could be an artifact of the flaky test assumptions around process creation/deletion tracked here: https://github.com/facebook/osquery/issues/1198

@jacknagz this is reproducible on master, without your custom merges?

**Comment by jacknagz** [comment]
@theopolis yep, just tested it on fb#master

**Comment by jacknagz** [comment]
Even after this commit (on a fresh pull from 1.5.1), I'm still seeing the same issue on my rhel6.6/rhel7.1 builds:

```
7:43:48 -- Building for platform RHEL (rhel, rhel6)
17:43:52 -- Building osquery version  1.5.1-203-gd74bf44 sdk 1.5.1
17:43:52 -- Configuring done
17:43:52 -- Generating done
17:43:52 -- Build files have been written to: /app_root/build/rhel6
17:43:53 Running tests...
17:43:53 Test project /app_root/build/rhel6
17:43:53     Start 1: osquery_tests
17:43:53 1/9 Test #1: osquery_tests ....................   Passed    0.14 sec
17:43:58     Start 2: osquery_additional_tests
17:43:58 2/9 Test #2: osquery_additional_tests .........   Passed    5.46 sec
17:43:58     Start 3: osquery_tables_tests
17:43:58 3/9 Test #3: osquery_tables_tests .............   Passed    0.10 sec
17:44:06     Start 4: python_test_osqueryi
17:44:06 4/9 Test #4: python_test_osqueryi .............   Passed    7.50 sec
17:44:12     Start 5: python_test_osqueryd
17:44:12 5/9 Test #5: python_test_osqueryd .............***Failed    5.85 sec
17:44:12 .I0817 17:44:06.725888 15132 config.cpp:137] Verbose logging enabled by config option
17:44:12 I0817 17:44:06.726446 15132 kernel.cpp:33] Cannot connect to kernel. Could not open character device.
17:44:12 I0817 17:44:06.727057 15134 events.cpp:497] Starting event publisher run loop: kernel
17:44:12 I0817 17:44:06.727073 15133 events.cpp:497] Starting event publisher run loop: inotify
17:44:12 I0817 17:44:06.727073 15135 events.cpp:497] Starting event publisher run loop: udev
17:44:12 I0817 17:44:06.747230 15134 events.cpp:507] Event publisher kernel run loop terminated for reason: No kernel communication.
17:44:12 .F
17:44:12 ======================================================================
17:44:12 FAIL: test_3_daemon_with_watchdog (__main__.DaemonTests)
17:44:12 ----------------------------------------------------------------------
17:44:12 Traceback (most recent call last):
17:44:12   File "/app_root/tools/tests/test_osqueryd.py", line 67, in test_3_daemon_with_watchdog
17:44:12     self.assertTrue(daemon.isDead(children[0]))
17:44:12 AssertionError
17:44:12 
17:44:12 ----------------------------------------------------------------------
17:44:12 Ran 3 tests in 5.708s
17:44:12 
17:44:12 FAILED (failures=1)
17:44:12 
17:44:15     Start 6: python_test_modules
17:44:15 6/9 Test #6: python_test_modules ..............   Passed    3.14 sec
17:44:20     Start 7: python_test_extensions
17:44:20 7/9 Test #7: python_test_extensions ...........   Passed    4.94 sec
17:44:21     Start 8: python_test_additional
17:44:21 8/9 Test #8: python_test_additional ...........   Passed    1.31 sec
17:44:23     Start 9: python_test_example_queries
17:44:23 9/9 Test #9: python_test_example_queries ......   Passed    2.52 sec
17:44:23 
17:44:23 89% tests passed, 1 tests failed out of 9
17:44:23 
17:44:23 Total Test time (real) =  30.98 sec
17:44:23 
17:44:23 The following tests FAILED:
17:44:23 	  5 - python_test_osqueryd (Failed)
17:44:23 Errors while running CTest
17:44:23 make[1]: *** [test] Error 8
17:44:24 make: *** [test] Error 2
```

**Comment by sharvilshah** [comment]
While I don't have access to RHEL, I can't reproduce this. I tested with CentOS{6.5,7} and both psutil 2.2.1 and psutil 3.1.1. Nothing in the [deprecated API](http://grodola.blogspot.com/2014/01/psutil-20-porting.html) jumps out.

Some more info about your env will be useful @jacknagz. 
What python/psutil version are you running?

You can check with:
`python -c "import sys,psutil; print 'python: \n' + sys.version; print 'psutil: \n' + psutil.__version__"`

And it should give an output like:
```
python:
2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
psutil:
2.2.1
```

**Comment by jacknagz** [comment]
Hey @sharvilshah, looks like I'm on an older version of python than you guys, could that be the issue?

```
# python -c "import sys,psutil; print 'python: \n' + sys.version; print 'psutil: \n' + psutil.__version__"
python:
2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
psutil:
3.1.1
```

**Comment by sharvilshah** [comment]
I don't think it's a python issue. CentOS is on python 2.6.6 as well.

**Comment by jacknagz** [comment]
@sharvilshah let's go ahead and close this out, it looks like an issue with my build system.  I'll investigate on my own.  

Thanks!
