### ISSUE TITLE
Can't build on Mac OS X 10.9.5 (13F1112)

### ISSUE THREAD

**Issue by pathcl** [facebook/osquery#1581]
I've just cloned and tried 'make deps'

```
tarro:osquery lsanmartin$ make deps
./tools/provision.sh build build/darwin10.9
[+] detected mac os x (10.9)
Updated Homebrew from 2950e5ab to 29509ca6.
Updated 1 tap (caskroom/cask).
No changes to formulae.
[+] wget is already installed. skipping.
[+] cmake is already installed. skipping.
[+] makedepend is already installed. skipping.
[+] doxygen is already installed. skipping.
[+] boost is already installed. skipping.
[+] gflags is already installed. skipping.
[+] lz4 is already installed. skipping.
[+] snappy is already installed. skipping.
[+] rocksdb is already installed. skipping.
[+] thrift is already installed. skipping.
[+] yara is already installed. skipping.
[+] libressl is already installed. skipping.
[+] cpp-netlib is already installed. skipping.
[+] google-benchmark is already installed. skipping.
[+] libmagic is already installed. skipping.
Password:
The directory '/Users/lsanmartin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/lsanmartin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): Jinja2 in /Users/lsanmartin/.pyenv/versions/3.6-dev/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): psutil in /Users/lsanmartin/.pyenv/versions/3.6-dev/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): argparse in /Users/lsanmartin/.pyenv/versions/3.6-dev/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pexpect in /Users/lsanmartin/.pyenv/versions/3.6-dev/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): thrift in /Users/lsanmartin/.pyenv/versions/3.6-dev/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Users/lsanmartin/.pyenv/versions/3.6-dev/lib/python3.6/site-packages (from Jinja2->-r requirements.txt (line 1))
HEAD is now at f5a9196 Merge pull request #9 from osquery/remove-benchmark
tarro:osquery lsanmartin$ make
cd build/darwin10.9 && cmake ../../ && \
		CTEST_OUTPUT_ON_FAILURE=1 make --no-print-directory
-- The C compiler identification is AppleClang 6.0.0.6000057
-- The CXX compiler identification is AppleClang 6.0.0.6000057
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building for platform OS X (darwin, 10.9)
-- Building osquery version  1.5.3-42-g3f8cb14 sdk 1.5.3
-- Found BZip2: /usr/lib/libbz2.dylib (found version "1.0.6")
-- Looking for BZ2_bzCompressInit in /usr/lib/libbz2.dylib
-- Looking for BZ2_bzCompressInit in /usr/lib/libbz2.dylib - found
-- Found library /usr/lib/libdl.dylib
-- Found library /usr/lib/libreadline.dylib
-- Found library /usr/lib/libncurses.dylib
-- Found OpenSSL: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib (found version "0.9.8z")
-- Looking for TLSv1_2_client_method in /usr/lib/libssl.dylib
-- Looking for TLSv1_2_client_method in /usr/lib/libssl.dylib - not found
-- Looking for TLSv1_1_client_method in /usr/lib/libssl.dylib
-- Looking for TLSv1_1_client_method in /usr/lib/libssl.dylib - not found
-- Looking for TLSv1_client_method in /usr/lib/libssl.dylib
-- Looking for TLSv1_client_method in /usr/lib/libssl.dylib - found
-- Found osquery-built library /third-party/glog/lib/libglog.a
-- Found library /usr/local/lib/libgflags.a
-- Found PythonInterp: /Users/lsanmartin/.pyenv/shims/python (found version "3.6")
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found library /usr/local/lib/librocksdb_lite.a
-- Found library /usr/local/lib/libsnappy.a
-- Found library /usr/local/lib/libthrift.a
-- Found library /usr/local/lib/libboost_thread-mt.a
-- Found library /usr/local/lib/liblz4.a
-- Found library /usr/local/lib/libboost_system.a
-- Found library /usr/local/lib/libboost_filesystem.a
-- Found library /usr/local/lib/libboost_regex.a
-- Found library /usr/local/lib/libyara.a
-- Found library /usr/local/lib/libcppnetlib-uri.a
-- Found library /usr/local/lib/libcppnetlib-client-connections.a
-- Found library /usr/lib/libarchive.dylib
-- Found library /usr/local/lib/libmagic.a
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.10")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/lsanmartin/src/osquery/build/darwin10.9
Scanning dependencies of target libglog
[  1%] Creating directories for 'libglog'
[  1%] No download step for 'libglog'
[  2%] No patch step for 'libglog'
[  2%] No update step for 'libglog'
[  2%] Performing configure step for 'libglog'
-- libglog configure command succeeded.  See also /Users/lsanmartin/src/osquery/build/darwin10.9/libglog-prefix/src/libglog-stamp/libglog-configure-*.log
[  2%] Performing build step for 'libglog'
-- libglog build command succeeded.  See also /Users/lsanmartin/src/osquery/build/darwin10.9/libglog-prefix/src/libglog-stamp/libglog-build-*.log
[  2%] Performing install step for 'libglog'
-- libglog install command succeeded.  See also /Users/lsanmartin/src/osquery/build/darwin10.9/libglog-prefix/src/libglog-stamp/libglog-install-*.log
[  2%] Completed 'libglog'
[  2%] Built target libglog
Scanning dependencies of target gtest
[  3%] Building CXX object third-party/gtest-1.7.0/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  3%] Linking CXX static library libgtest.a
[  3%] Built target gtest
Scanning dependencies of target gtest_main
[  3%] Building CXX object third-party/gtest-1.7.0/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[  4%] Linking CXX static library libgtest_main.a
[  4%] Built target gtest_main
Scanning dependencies of target osquery_sqlite
[  4%] Building C object third-party/sqlite3/CMakeFiles/osquery_sqlite.dir/sqlite3.c.o
/Users/lsanmartin/src/osquery/third-party/sqlite3/sqlite3.c:8954:26: warning: unused variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
[  4%] Built target osquery_sqlite
[  5%] Generating ../../generated/gen-cpp/Extension.cpp, ../../generated/gen-cpp/Extension.h, ../../generated/gen-cpp/ExtensionManager.cpp, ../../generated/gen-cpp/ExtensionManager.h, ../../generated/gen-cpp/osquery_types.cpp, ../../generated/gen-cpp/osquery_types.h
Scanning dependencies of target osquery_extensions
[  5%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/Extension.cpp.o
[  5%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/ExtensionManager.cpp.o
[  6%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/osquery_types.cpp.o
[  6%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/extensions.cpp.o
[  6%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/interface.cpp.o
[  6%] Built target osquery_extensions
Scanning dependencies of target osquery_tables
[  7%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/applications/browser_chrome.cpp.o
[  7%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/applications/browser_firefox.cpp.o
[  7%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/applications/browser_opera.cpp.o
[  8%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/applications/browser_utils.cpp.o
[  8%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/cpuid.cpp.o
[  8%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/crontab.cpp.o
[  9%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/last.cpp.o
[  9%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/logged_in_users.cpp.o
[  9%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/magic.cpp.o
[ 10%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/shell_history.cpp.o
[ 10%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/smbios_utils.cpp.o
[ 10%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/suid_bin.cpp.o
[ 11%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/system_controls.cpp.o
[ 11%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/system/uptime.cpp.o
[ 11%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/networking/etc_hosts.cpp.o
[ 12%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/networking/etc_protocols.cpp.o
[ 12%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/networking/etc_services.cpp.o
[ 12%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/networking/interfaces.cpp.o
[ 12%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/networking/listening_ports.cpp.o
[ 13%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/networking/utils.cpp.o
[ 13%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/events/file_access_events.cpp.o
[ 13%] Building CXX object osquery/tables/CMakeFiles/osquery_tables.dir/events/yara_events.cpp.o
[ 13%] Built target osquery_tables
[ 14%] Generating ../generated/tables_additional/xprotect_reports.cpp
Traceback (most recent call last):
  File "/Users/lsanmartin/src/osquery/tools/codegen/gentable.py", line 366, in <module>
    main(len(sys.argv), sys.argv)
  File "/Users/lsanmartin/src/osquery/tools/codegen/gentable.py", line 354, in main
    setup_templates(args.templates)
  File "/Users/lsanmartin/src/osquery/tools/codegen/gentable.py", line 124, in setup_templates
    TEMPLATES[template_name] = fh.read().replace("\\\n", "")
TypeError: a bytes-like object is required, not 'str'
make[3]: *** [generated/tables_additional/xprotect_reports.cpp] Error 1
make[2]: *** [osquery/CMakeFiles/osquery_additional_amalgamation.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

tarro:osquery lsanmartin$ python -V
Python 3.6.0a0
```

**Comment by sharvilshah** [comment]
I don't have access to a 10.9 system anymore. Can you give this a try with system python (I believe Apple ships with 2.7). That can help narrow it down.

**Comment by pathcl** [comment]
@sharvilshah indeed now it works flawlessly. At least this system ships with '2.7.5'. One little thing: it tries to uses 'pip' but what if I dont have it? it should suggest to try 'easy_install pip' imho

**Comment by sharvilshah** [comment]
@pathcl AFAIK Apple has always shipped python 2.x at least since 10.5 Leopard. 

I haven't kept up with python3 developments as much as I would have liked, but I think the priority is to have it work with system default python 2.x (@theopolis feel free to correct me). If you know the offending stdlib call that's changed, feel free to update `gentable.py` and `genapi.py` and submit a PR :) 

If the system doesn't have `pip` installed, it will complain and ask to install it. That's implemented here: https://github.com/facebook/osquery/blob/master/tools/provision/darwin.sh#L16

**Comment by marpaia** [comment]
Cool, since @sharvilshah seems to have resolved all of the issues here, I think this is cool to be closed? We don't currently support python3, just because we don't use it very much, so a PR for that would be awesome :)

**Comment by pathcl** [comment]
@marpaia why are you using 'rb' at https://github.com/facebook/osquery/blob/master/tools/codegen/gentable.py#L123 ? I've just replaced as 'rt' and now got it compiled with python 3.6.0a0
