### ISSUE TITLE
Flaky test: python_test_osqueryi: pexpect waiting for shell prompt

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2361]
See:
```
4/9 Test #4: python_test_osqueryi .............***Failed  101.39 sec
.E.........
======================================================================
ERROR: test_config_check_example (__main__.OsqueryiTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/ubuntu14/tools/tests/test_osqueryi.py", line 29, in setUp
    self.osqueryi = test_base.OsqueryWrapper(self.binary)
  File "/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/ubuntu14/tools/tests/test_base.py", line 109, in __init__
    continuation_prompt=self.CONTINUATION_PROMPT)
  File "/usr/local/osquery/Cellar/python/2.7.12/lib/python2.7/site-packages/pexpect/replwrap.py", line 55, in __init__
    self._expect_prompt()
  File "/usr/local/osquery/Cellar/python/2.7.12/lib/python2.7/site-packages/pexpect/replwrap.py", line 66, in _expect_prompt
    timeout=timeout)
  File "/usr/local/osquery/Cellar/python/2.7.12/lib/python2.7/site-packages/pexpect/spawnbase.py", line 390, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/osquery/Cellar/python/2.7.12/lib/python2.7/site-packages/pexpect/expect.py", line 107, in expect_loop
    return self.timeout(e)
  File "/usr/local/osquery/Cellar/python/2.7.12/lib/python2.7/site-packages/pexpect/expect.py", line 70, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x2b17fabd6790>
command: /home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/ubuntu14/build/trusty/osquery/osqueryi
args: ['/home/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/ubuntu14/build/trusty/osquery/osqueryi', '--database_path=/tmp/osquery-tests-python1000/tests.db8436', '--force=true', '--config_path=/tmp/osquery-tests-python1000/tests.conf', '--disable_events=true', '--watchdog_level=3', '--disable_logging=true', '--extensions_socket=/tmp/osquery-tests-python1000/tests.em', '--extensions_timeout=0', '--extensions_interval=1', '--pidfile=/tmp/osquery-tests-python1000/tests.pid']
buffer (last 100 chars): ''
before (last 100 chars): ''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 28164
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: "osquery> "
    1: "    ...> "
```

Example: https://jenkins.osquery.io/job/osqueryPullRequestBuild/TargetSystem=ubuntu14/lastBuild/console

**Comment by theopolis** [comment]
This output (waiting for expect prompt) is displayed when something else fails in the client. For a better testing/error-isolation experience we should not be printing these red-herrings and rather display the `stdout`, `stderr` from the binary.

**Comment by theopolis** [comment]
Not seeing this anymore, we can re-open with more data if it occurs again.
