### ISSUE TITLE
apt_sources does not return results as root

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2874]
The root user will drop privileges to `nobody` on Ubuntu. It seems this prevents `apt_sources` from returning data. The table relies on shared-library-internal resources, the drop of credentials is affected somehow.

**Comment by theopolis** [comment]
There may be a more severe issue, caused by the upgrade of `libapt-pkg`, when used on non-Debian based systems.

Upgrade: https://github.com/facebook/osquery/commit/d3db14337e0b17f1aaef6fb3390540f9bee3a461#diff-aea780dc0ed9ed1891c2966b697d3a5cR6

**Comment by theopolis** [comment]
Trace when running on CentOS7:
```
#0  0x00007ffff6ebc702 in pkgCacheGenerator::MakeStatusCache(pkgSourceList&, OpProgress*, MMap**, pkgCache**, bool) () from /vagrant/build/centos7/osquery/libosquery_additional.so
#1  0x00007ffff6e93cdb in pkgCacheFile::BuildCaches(OpProgress*, bool) () from /vagrant/build/centos7/osquery/libosquery_additional.so
#2  0x00007ffff69d1a3b in osquery::tables::genAptSrcs(osquery::QueryContext&) () from /vagrant/build/centos7/osquery/libosquery_additional.so
#3  0x00007ffff6a4a014 in osquery::aptSourcesTablePlugin::generate(osquery::QueryContext&) () from /vagrant/build/centos7/osquery/libosquery_additional.so
#4  0x00007ffff7a6f2c1 in osquery::RegistryFactory::callTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, osquery::QueryContext&, std::vector<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::allocator<std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >&) () from /vagrant/build/centos7/osquery/libosquery.so
#5  0x00007ffff69aea03 in osquery::tables::sqlite::xFilter(sqlite3_vtab_cursor*, int, char const*, int, Mem**) () from /vagrant/build/centos7/osquery/libosquery_additional.so
#6  0x00007ffff7986620 in sqlite3VdbeExec () from /vagrant/build/centos7/osquery/libosquery.so
#7  0x00007ffff7967271 in sqlite3_step () from /vagrant/build/centos7/osquery/libosquery.so
#8  0x000000000040dac3 in shell_exec(char const*, int (*)(void*, int, char**, char**, int*), callback_data*, char**) ()
#9  0x000000000040f745 in do_meta_command(char*, callback_data*) ()
#10 0x000000000040ec6c in osquery::launchIntoShell(int, char**) ()
#11 0x0000000000415b59 in main ()
```
