### ISSUE TITLE
Possible race condition in osqueryi when running queries from the command line

### ISSUE THREAD

**Issue by koikonom** [facebook/osquery#2883]
I am using a program that passes osqueryi queries as arguments (or stdin) and then processes their results by reading stdout. This works fine for the builtin tables but I am seeing the following behavior when using a custom extension:

```
root@2c9da95d463b:/tmp# osqueryi --version
osqueryi version 2.2.1
root@2c9da95d463b:/tmp# echo 'select count(*) from puppet_facts;' | osqueryi --debug --verbose --extension /usr/bin/osquery-puppet-facts.ext
I1222 14:15:24.403262   405 init.cpp:364] osquery initialized [version=2.2.1]
I1222 14:15:24.403364   405 extensions.cpp:275] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I1222 14:15:24.403479   405 extensions.cpp:288] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I1222 14:15:24.403853   406 watcher.cpp:500] Created and monitoring extension child (409): /usr/bin/osquery-puppet-facts.ext
I1222 14:15:24.403930   408 interface.cpp:307] Extension manager service starting: /root/.osquery/shell.em
I1222 14:15:24.403993   405 init.cpp:606] Error reading config: config file does not exist: /etc/osquery/osquery.conf
I1222 14:15:24.404064   405 events.cpp:909] Error registering subscriber: socket_events: Subscriber disabled via configuration
Error: near line 1: no such table: puppet_facts
root@2c9da95d463b:/tmp# Traceback (most recent call last):
  File "/usr/bin/osquery-puppet-facts.ext", line 9, in <module>
    load_entry_point('osquery-extensions==0.0.1', 'console_scripts', 'osquery-puppet-facts.ext')()
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/osquery_extensions/facts.py", line 37, in main
    version='0.0.1',)
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/osquery/management.py", line 160, in start_extension
    client.open()
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/osquery/extension_client.py", line 46, in open
    self._transport.open()
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 149, in open
    return self.__trans.open()
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/thrift/transport/TSocket.py", line 101, in open
    message=message)
thrift.transport.TTransport.TTransportException: Could not connect to socket /root/.osquery/shell.em

root@2c9da95d463b:/tmp#
root@2c9da95d463b:/tmp# osqueryi 'select count(*) from puppet_facts;' --debug --verbose --extension /usr/bin/osquery-puppet-facts.ext
I1222 14:15:46.925251   410 init.cpp:364] osquery initialized [version=2.2.1]
I1222 14:15:46.925360   410 extensions.cpp:275] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I1222 14:15:46.925477   410 extensions.cpp:288] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I1222 14:15:46.931280   411 watcher.cpp:500] Created and monitoring extension child (412): /usr/bin/osquery-puppet-facts.ext
I1222 14:15:46.931546   414 interface.cpp:307] Extension manager service starting: /root/.osquery/shell.em
I1222 14:15:46.931622   410 init.cpp:606] Error reading config: config file does not exist: /etc/osquery/osquery.conf
I1222 14:15:46.931674   410 events.cpp:909] Error registering subscriber: socket_events: Subscriber disabled via configuration
Error: no such table: puppet_facts
root@2c9da95d463b:/tmp# Traceback (most recent call last):
  File "/usr/bin/osquery-puppet-facts.ext", line 9, in <module>
    load_entry_point('osquery-extensions==0.0.1', 'console_scripts', 'osquery-puppet-facts.ext')()
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/osquery_extensions/facts.py", line 37, in main
    version='0.0.1',)
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/osquery/management.py", line 160, in start_extension
    client.open()
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/osquery/extension_client.py", line 46, in open
    self._transport.open()
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 149, in open
    return self.__trans.open()
  File "/usr/share/python/osquery-extensions/local/lib/python2.7/site-packages/thrift/transport/TSocket.py", line 101, in open
    message=message)
thrift.transport.TTransport.TTransportException: Could not connect to socket /root/.osquery/shell.em

root@2c9da95d463b:/tmp# osqueryi --debug --verbose --extension /usr/bin/osquery-puppet-facts.ext
I1222 14:15:57.489749   415 init.cpp:364] osquery initialized [version=2.2.1]
I1222 14:15:57.489833   415 extensions.cpp:275] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I1222 14:15:57.489938   415 extensions.cpp:288] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I1222 14:15:57.490120   418 interface.cpp:307] Extension manager service starting: /root/.osquery/shell.em
I1222 14:15:57.490380   416 watcher.cpp:500] Created and monitoring extension child (419): /usr/bin/osquery-puppet-facts.ext
I1222 14:15:57.490434   415 init.cpp:606] Error reading config: config file does not exist: /etc/osquery/osquery.conf
I1222 14:15:57.490525   415 events.cpp:909] Error registering subscriber: socket_events: Subscriber disabled via configuration
Using a virtual database. Need help, type '.help'
osquery> I1222 14:15:57.615967   420 interface.cpp:130] Registering extension (osquery_puppet_facts_extension, 39756, version=0.0.1, sdk=1.8.0)
I1222 14:15:57.616344   420 registry.cpp:364] Extension 39756 registered table plugin puppet_facts

osquery> select count(*) from puppet_facts;
+----------+
| count(*) |
+----------+
| 2        |
+----------+
osquery>

I1222 14:16:06.748513   417 extensions.cpp:170] Extension UUID 39756 shutdown request failed
root@2c9da95d463b:/tmp#
```

It looks like osqueryi is trying to run the query I pass (either via stdin or via command line arguments) before my extension is registered, which results in seeing the message "Error: no such table: puppet_facts". I also think that the python stacktrace I see is happening because by the time my extsnsion tries to register with osqueryi, the unix socket is closed since the osqueryi process has exited.

As a test I edited osquery/devtools/shell.cpp and added an arbitrary sleep in launchIntoShell() a bit before it calls runQuery() and I was able to run queries from the command line, which makes me feel more confident about calling this a race condition, but it's far from an actual fix and I don't know C++ to submit a proper fix myself :). 

Let me know if I can provide more information.

Thanks

**Comment by theopolis** [comment]
Thanks @koikonom, we'll check this out.

**Comment by theopolis** [comment]
Ok, you are correct! The osquery application is loading your extension and once it comes online (responds to a quick Thrift ping) the execution continues-- this is where SQL begins to scan for your table. The "skipped" step is waiting for your extension to finish it's work on broadcasting and registering all of it's plugins. We can solve this by asking osquery to wait for an extension using the `--extensions_require` flag: http://osquery.readthedocs.io/en/stable/installation/cli-flags/

It looks like you'll want:
```
echo 'select count(*) from puppet_facts;' | \
  osqueryi --debug --verbose --extension /usr/bin/osquery-puppet-facts.ext --extensions_require=osquery_puppet_facts_extension
```

**Comment by koikonom** [comment]
That works fine! Thank you for your help.
