### ISSUE TITLE
Not working in Python 3. ( Error: No Module named ttypes)

### ISSUE THREAD

**Issue by MobeenAshraf** [facebook/osquery#3037]
osquery-python scripts aren't running in python 3.  I am getting following error : 

`Traceback (most recent call last):
  File "C:/Users/Mobeen/Documents/GitHub/osquery-python/examples/foobar_table.py", line 7, in <module>
    import osquery
  File "C:\Users\Mobeen\Documents\GitHub\osquery-python\osquery\__init__.py", line 33, in <module>
    from osquery.extension_client import DEFAULT_SOCKET_PATH, ExtensionClient
  File "C:\Users\Mobeen\Documents\GitHub\osquery-python\osquery\extension_client.py", line 17, in <module>
    from osquery.extensions.ExtensionManager import Client
  File "C:\Users\Mobeen\Documents\GitHub\osquery-python\osquery\extensions\ExtensionManager.py", line 10, in <module>
    import osquery.extensions.Extension
  File "C:\Users\Mobeen\Documents\GitHub\osquery-python\osquery\extensions\Extension.py", line 11, in <module>
    from ttypes import *
ModuleNotFoundError: No module named 'ttypes'`

I think this  [link](https://github.com/elastic/elasticsearch-py/issues/184), can provide more details on this issue. 

Changing python version to 2.x does the job !

**Comment by MobeenAshraf** [comment]
Was added by mistake. It was supposed to be added on osquery-python's repo
