### ISSUE TITLE
Cannot build on arch linux.

### ISSUE THREAD

**Issue by jkbbwr** [facebook/osquery#3288]
Tried building from source on Arch. 
```
/usr/local/osquery/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:338:in `fetch_issues'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:334:in `issues'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:388:in `dump'
	from /usr/local/osquery/Library/Homebrew/brew.rb:130:in `rescue in <main>'
	from /usr/local/osquery/Library/Homebrew/brew.rb:31:in `<main>'
make: *** [Makefile:123: deps] Error 1
```

Can we provide an official pacman package?

**Comment by jkbbwr** [comment]
Also does it really need to install brew to be usable? Seems a bit overkill.

**Comment by theopolis** [comment]
Hi @jkbbwr, here's the theory for the `make deps` and local `brew` usage: http://osquery.readthedocs.io/en/stable/development/building/#dependencies-and-build-internals

Brew and the dependencies are not required to use `osquery`, just to build a universal/deployable `osquery`. If you check out https://github.com/facebook/osquery/pull/3062 @tonylambiris is helping make `osquery` buildable within Arch's build system. There have been changes to master that need to be updated, but some of them get the repo into a better position to build within the system's native builder.

**Comment by tonylambiris** [comment]
@jkbbwr I've been slacking on the arch package but will queue it after this build of the linux-macbook kernel I maintain finishes compilation.

Thanks for tying me into the conversation @theopolis

**Comment by tonylambiris** [comment]
Just a heads up to all arch users, just updated the [osquery-git](https://aur.archlinux.org/packages/osquery-git/) using the latest commit hash at the time of this writing (62beb1e547622d63ca8793d4bc2f8eafc26e0c47).

**Comment by nbigaouette-eai** [comment]
I'm having the same issue, but on macOS (not Arch).

I'm attempting to use `OSQUERY_DEPS` to place build dependencies in a non-default location (see #3373) but building the dependencies from source is failing with this error.

Here's the end of the log when using both `OSQUERY_DEPS` and `OSQUERY_BUILD_DEPS=1`:
```
[+] brew package osquery/osquery-local/augeas installing new version: 1.8.0_101
==> Installing augeas from osquery/osquery-local
==> Cloning https://github.com/hercules-team/augeas.git
Updating /Users/nbigaouette/deps_dir/.cache/augeas--git
==> Checking out revision f66a71dc22c0536853bb99585a4bf605018ba6db
==> Patching
patching file configure.ac
Hello from osquery setup: augeas
==> ./autogen.sh --without-selinux --prefix=/Users/nbigaouette/deps_dir/Cellar/augeas/1.8.0_101
==> ./configure --without-selinux --prefix=/Users/nbigaouette/deps_dir/Cellar/augeas/1.8.0_101 --enable-shared=no
==> make
==> make datadir.h
==> make install-libLTLIBRARIES
Last 15 lines from /Users/nbigaouette/Library/Logs/Homebrew/augeas/05.make:
1 warning generated.
syntax.c:71:19: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
static const char const anon_ident[] = "_";
                  ^
../gnulib/lib/argz.h:29:16: note: expanded from macro 'const'
# define const const
               ^
  YACC     parser.c
8 warnings generated.
  CC       builtin.lo
/private/tmp/augeas-20170605-42094-uneqc8/src/parser.y:46.1-5: invalid directive: `%code'
/private/tmp/augeas-20170605-42094-uneqc8/src/parser.y:46.7-14: syntax error, unexpected identifier
make[2]: *** [parser.c] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
osquery/osquery-local

/Users/nbigaouette/deps_dir/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
        from /Users/nbigaouette/deps_dir/Library/Homebrew/utils/github.rb:184:in `open'
        from /Users/nbigaouette/deps_dir/Library/Homebrew/utils/github.rb:233:in `issues_matching'
        from /Users/nbigaouette/deps_dir/Library/Homebrew/utils/github.rb:272:in `issues_for_formula'
        from /Users/nbigaouette/deps_dir/Library/Homebrew/exceptions.rb:368:in `fetch_issues'
        from /Users/nbigaouette/deps_dir/Library/Homebrew/exceptions.rb:364:in `issues'
        from /Users/nbigaouette/deps_dir/Library/Homebrew/exceptions.rb:418:in `dump'
        from /Users/nbigaouette/deps_dir/Library/Homebrew/brew.rb:131:in `rescue in <main>'
        from /Users/nbigaouette/deps_dir/Library/Homebrew/brew.rb:30:in `<main>'
make[1]: *** [deps] Error 1
make: *** [/Users/nbigaouette/deps_dir/osquery_deps_ready] Error 2
```

**Comment by theopolis** [comment]
@tonylambiris, the `-mt` issues should now be resolved, let me know if the port still requires a patch.

@nbigaouette-eai, you'll need a newer version of `bison` installed to build from source unfortunately.

Please feel free to re-open if there are issues with Arch still. :)

**Comment by tonylambiris** [comment]
@theopolis Nope, hadn't needed the `-mt` hack for some time now. Thanks!
