### ISSUE TITLE
bug: deps: sometimes distutils.cfg includes tabs on linux

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#4587]
See: https://jenkins.osquery.io/job/osqueryMasterPackagesPosix/1625/TargetSystem=aws-ubuntu-16.04/console

Very odd observation, I cannot reproduce but at least one Ubuntu16.04 build host had this behavior:
```
cat /usr/local/osquery/Cellar/python/2.7.12_201/lib/python2.7/distutils/distutils.cfg
      [install]
      prefix=/usr/local/osquery

      [build_ext]
      include_dirs=/usr/local/osquery/include:/usr/local/osquery/legacy/include:/usr/local/osquery/opt/openssl/include
      library_dirs=/usr/local/osquery/lib:/usr/local/osquery/legacy/lib:/usr/local/osquery/opt/openssl/lib
```

The expected content of this file is:
```
[install]
prefix=/usr/local/osquery

[build_ext]
include_dirs=/usr/local/osquery/include:/usr/local/osquery/legacy/include:/usr/local/osquery/opt/openssl/include
library_dirs=/usr/local/osquery/lib:/usr/local/osquery/legacy/lib:/usr/local/osquery/opt/openssl/lib
```

Perhaps there is a recent side-effect from updating the dependencies to Python `2.7.12_201`. 

In the build logs you will find:
```
[+] upgrading pip and installing python dependencies
Collecting pip
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
Installing collected packages: pip
Exception:
Traceback (most recent call last):
  File "/usr/local/osquery/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/osquery/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/osquery/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/osquery/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/osquery/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/osquery/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/osquery/lib/python2.7/site-packages/pip/locations.py", line 141, in distutils_scheme
    d.parse_config_files()
  File "/usr/local/osquery/Cellar/python/2.7.12_201/lib/python2.7/distutils/dist.py", line 390, in parse_config_files
    parser.read(filename)
  File "/usr/local/osquery/Cellar/python/2.7.12_201/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/local/osquery/Cellar/python/2.7.12_201/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: /usr/local/osquery/Cellar/python/2.7.12_201/lib/python2.7/distutils/distutils.cfg, line: 1
'      [install]\n'
```

As a symptom.

**Comment by theopolis** [comment]
Fixed with: #4584
