### ISSUE TITLE
osqueryi coredump when run command ".exit or .quit"

### ISSUE THREAD

**Issue by shuzhifeng** [facebook/osquery#559]
$./osqueryi 
osquery> .quit
pure virtual method called
terminate called without an active exception
Aborted (core dumped)

**Comment by theopolis** [comment]
Found this again on CentOS, some research suggests a problem with not using llvm's c++ supc++ implementations but I think it's a race condition where we delete some shared space that accessed late by the event publishers:

```
Starting program: /vagrant/build/centos/osquery/osqueryi "select * from time"
[Thread debugging using libthread_db enabled]
[New Thread 0x7fffec4ff700 (LWP 3433)]
[New Thread 0x7fffebafe700 (LWP 3434)]

+------+---------+---------+
| hour | minutes | seconds |
+------+---------+---------+
| 16   | 11      | 29      |
+------+---------+---------+
pure virtual method called
terminate called without an active exception

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffec4ff700 (LWP 3433)]
0x00007ffff5529625 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5529625 in raise () from /lib64/libc.so.6
#1  0x00007ffff552ae05 in abort () from /lib64/libc.so.6
#2  0x00007ffff5de3a7d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib64/libstdc++.so.6
#3  0x00007ffff5de1bd6 in ?? () from /usr/lib64/libstdc++.so.6
#4  0x00007ffff5de1c03 in std::terminate() () from /usr/lib64/libstdc++.so.6
#5  0x00007ffff5de255f in __cxa_pure_virtual () from /usr/lib64/libstdc++.so.6
#6  0x0000000000523e00 in osquery::EventSubscriberCore::dbNamespace() ()
#7  0x000000000051f375 in osquery::EventSubscriberCore::getEventID() ()
#8  0x0000000000520c1c in osquery::EventSubscriberCore::add(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int) ()
#9  0x00000000005551c2 in osquery::tables::PasswdChangesEventSubscriber::Callback(std::shared_ptr<osquery::INotifyEventContext> const&) ()
#10 0x0000000000555e08 in std::_Function_handler<osquery::Status ()(std::shared_ptr<osquery::EventContext> const&), std::_Bind<std::_Mem_fn<osquery::Status (osquery::tables::PasswdChangesEventSubscriber::*)(std::shared_ptr<osquery::EventContext> const&)> ()(osquery::tables::PasswdChangesEventSubscriber*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, std::shared_ptr<osquery::EventContext> const&)
    ()
#11 0x000000000051479e in osquery::EventPublisher<osquery::INotifySubscriptionContext, osquery::INotifyEventContext>::fireCallback(std::shared_ptr<osquery::Subscription> const&, std::shared_ptr<osquery::EventContext> const&) ()
#12 0x0000000000518e40 in osquery::EventPublisherCore::fire(std::shared_ptr<osquery::EventContext> const&, unsigned int) ()
#13 0x0000000000512d98 in osquery::INotifyEventPublisher::run() ()
#14 0x0000000000521da1 in osquery::EventFactory::run(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#15 0x0000000000526f1c in boost::detail::thread_data<boost::_bi::bind_t<osquery::Status, osquery::Status (*)(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), boost::_bi::list1<boost::_bi::value<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::run() ()
#16 0x0000000000691960 in boost::(anonymous namespace)::thread_proxy(void*) ()
#17 0x00007ffff7bc79d1 in start_thread () from /lib64/libpthread.so.0
#18 0x00007ffff55df8fd in clone () from /lib64/libc.so.6
```
