### ISSUE TITLE
Build failure: Non ASCII Byte

### ISSUE THREAD

**Issue by jedi22** [facebook/osquery#695]
```
[  5%] Generating ../generated/tables_utils/hash.cpp
Traceback (most recent call last):
  File "/Users/obelisk/Desktop/osquery/git/osquery/tools/codegen/gentable.py", line 286, in <module>
    main(len(sys.argv), sys.argv)
  File "/Users/obelisk/Desktop/osquery/git/osquery/tools/codegen/gentable.py", line 275, in main
    setup_templates(filename)
  File "/Users/obelisk/Desktop/osquery/git/osquery/tools/codegen/gentable.py", line 100, in setup_templates
    TEMPLATES[template_name] = fh.read().replace("\\\n", "")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 330: ordinal not in range(128)
make[3]: *** [generated/tables_utils/hash.cpp] Error 1
make[2]: *** [osquery/CMakeFiles/osquery_utils_amalgamation.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by marpaia** [comment]
CC @theopolis

**Comment by theopolis** [comment]
What does `/tables/specs/x/hash.table` look like? Did you/anything edit this file recently?

**Comment by jedi22** [comment]
MD5: 5bfdb7afedd189c0ff6a5ca8cb1b65ee

```
table_name("hash")
schema([
    Column("path", TEXT, "Must provide a path or directory", required=True),
    Column("directory", TEXT, "Must provide a path or directory", required=True),
    Column("md5", TEXT),
    Column("sha1", TEXT),
    Column("sha256", TEXT),
])
implementation("utility/hash@genHash")
```

**Comment by jedi22** [comment]
Note, .DS_Store files will be seen as tables in spec folder, if those exist the build will fail.
